<?php

function commerce_userpoints_discount_menu() {

  $items = array();

  $items['admin/commerce/config/commerce_userpoints_discount'] = array(
    'title' => 'Commerce !points settings',
    'title arguments' => userpoints_translation(),
    'description' => 'Configure the commerce userpoints module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_userpoints_discount_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}

function commerce_userpoints_discount_admin() {
  $form = array();

  $form['commerce_userpoints_discount_default_termid'] = array(
    '#type' => 'select',
    '#title' => t('!Points category', userpoints_translation()),
    '#default_value' => variable_get('commerce_userpoints_discount_default_termid', userpoints_get_default_tid()),
    '#description' => t('Select the default !points category to use as "credit".', userpoints_translation()),
    '#options' => userpoints_get_categories(),
    '#required' => TRUE,
  );

  $price_components_options = array();
  $price_components_list = commerce_price_component_types();
  foreach($price_components_list as $price_component) {
    $price_components_options[$price_component['name']] = $price_component['name'];
  }
  unset($price_components_options['userpoints']);

  $form['commerce_userpoints_discount_total_price_components'] = array(
    '#type' => 'select',
    '#title' => t('Allowed price components'),
    '#default_value' => variable_get('commerce_userpoints_discount_total_price_components', array()),
    '#description' => t('Select the list of price component the credit can cover.'),
    '#options' => $price_components_options,
    '#multiple' => TRUE,
    '#size' => min(12, count($price_components_options)),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Implements hook_views_api().
 */
function commerce_userpoints_discount_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commerce_userpoints_discount') . '/includes/views',
  );
}

function commerce_userpoints_discount_commerce_checkout_pane_info() {
  $checkout_panes = array();

  $checkout_panes['commerce_userpoints_discount'] = array(
    'title' => t('Use my credits'),
    'page' => 'checkout',
    'locked' => TRUE,
    'file' => 'includes/commerce_userpoints_discount.checkout_pane.inc',
    'base' => 'commerce_userpoints_discount_pane',
    'weight' => 10,
  );
  return $checkout_panes;
}

/**
 * Implements hook_commerce_line_item_type_info()
 */
function commerce_userpoints_discount_commerce_line_item_type_info() {
  $line_item_types['userpoints'] = array(
    'type' => 'userpoints',
    'name' => t('!Points', userpoints_translation()),
    'description' => t('!Points value line item.', userpoints_translation()),
    'add_form_submit_value' => t('Use !points', userpoints_translation()),
    'base' => 'commerce_userpoints_discount_line_item',
    'callbacks' => array(
      'configuration' => 'commerce_userpoints_discount_configure_line_item'
    ),

  );
  return $line_item_types;
}

/**
 *
 * This function is called by the line item module when it is enabled or this
 * module is enabled. It invokes this function using the configuration_callback
 * as specified above.
 */

function commerce_userpoints_discount_configure_line_item() {
  $entity_type = 'commerce_line_item';
  $bundle = 'userpoints';

  // Look for or add the specified coupon code
  $field_name = 'commerce_userpoints_discount_txn';
  $field = field_info_field($field_name);
  $instance = field_info_instance($entity_type, $field_name, $bundle);

  if (empty($field)) {
    $field = array(
      'field_name' => $field_name,
      'type' => 'text',
      'cardinality' => 1,
      'entity_types' => array($entity_type),
      'translatable' => FALSE,
      'locked' => TRUE,
      'settings' => array(),
    );
    $field = field_create_field($field);
  }

  if (empty($instance)) {
    $instance = array(
      'field_name' => $field_name,
      'entity_type' => $entity_type,
      'bundle' => $bundle,
      'label' => t('!Points transaction reference', userpoints_translation()),
      'required' => FALSE,
      'settings' => array(),
      'display' => array(),
    );
    field_create_instance($instance);
  }
}

/**
 * Returns an appropriate title for this line item.
 */
function commerce_userpoints_discount_line_item_title($line_item) {
  return t('Utilisation de royalties');
}

/**
 * Returns the elements necessary to add a product line item through a line item
 * manager widget.
 */
function commerce_userpoints_discount_line_item_add_form($form_state) {
  $form = array();

  $form['amount'] = array(
    '#type' => 'textfield',
    '#title' => t('Amount'),
    '#default_value' => 0,
    '#size' => 10,
  );

  $form['current_points'] = array(
    '#type' => 'item',
    '#title' => t('User current !points', userpoints_translation()),
    //TODO: Display the correct points value related to the order owner rather than the currently logged in user
    //Related to this issue http://drupal.org/node/1233790
    '#markup' => check_plain(userpoints_get_current_points(NULL, variable_get('commerce_userpoints_discount_default_termid'))),
  );

  $form['currency_code'] = array(
    '#type' => 'select',
    '#title' => t('Currency'),
    '#options' => commerce_currency_code_options_list(),
    '#default_value' => commerce_default_currency(),
  );

  return $form;
}

/**
 * @param $line_item
 *   The newly created line item object.
 * @param $element
 *   The array representing the widget form element.
 * @param $form_state
 *   The present state of the form upon the latest submission.
 * @param $form
 *   The actual form array.
 *
 * @return
 *   NULL if all is well or an error message if something goes wrong.
 */
function commerce_userpoints_discount_line_item_add_form_submit(&$line_item, $element, &$form_state, $form) {
  // TODO: Implement this method correct
  $order = $form_state['commerce_order'];
  if($element['actions']['amount']['#value'] >= 0) {
    form_set_error("Illegal value", "The amount should be less than 0");
  }
  if ($element['actions']['amount']['#value'] > userpoints_get_current_points($order->uid, variable_get('commerce_userpoints_discount_default_termid'))) {
    form_set_error("Not enough credit", "The user don't have enough !points", userpoints_translation());
  }
  
  $userpoints_params = array(
    'points' => floatval($element['actions']['amount']['#value']),
    'uid' => $order->uid,
    'operation' => 'commerce_userpoints_discount_credit',
    'tid' => variable_get('commerce_userpoints_discount_default_termid', userpoints_get_default_tid()),
    'display' => FALSE,
    'entity_id' => $order->order_id,
    'entity_type' => 'commerce_order',
  );

  $result = userpoints_userpointsapi($userpoints_params);

  $label = "TXNID" . $result['transaction']['txn_id'];
  commerce_userpoints_discount_line_item_populate($line_item, $order->order_id, $result['transaction'], $element['actions']['currency_code']['#value'], $label, TRUE);
  return;
}

/**
 * Implements hook_userpoints_info().
 */
function commerce_userpoints_discount_userpoints_info() {
  return array(
    'commerce_userpoints_discount_credit' => array(
      'description' => t('Using credit for purchase'),
    ),
  );
}

/**
 * This function checks if an oder already have a userpoint line_item type attached to it.
 * @param  $order_id
 * @return line_item_id if exists, or NULL if not
 */
function commerce_userpoints_discount_order_has_userpoint_line_item($order_id) {
  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'commerce_line_item', '=')
    ->entityCondition('bundle', 'userpoints', '=')
    ->propertyCondition('order_id', $order_id, '=')
    ->execute();

  if(empty($result))
    return NULL;
  $line_item = array_shift($result['commerce_line_item']);
  return $line_item->line_item_id;
}

/**
 * Only one userpoints line item can be created for an order, if the order already have
 * a userpoints line item, it will be returned
 * @param  $order_id
 * @return void
 */
function commerce_userpoints_discount_line_item_factory_new($order_id) {
  $line_item_id = commerce_userpoints_discount_order_has_userpoint_line_item($order_id);
  if($line_item_id == NULL)
    return _commerce_userpoints_discount_line_item_new();

  return commerce_line_item_load($line_item_id);
}

/**
 * Creates a new product line item populated with the proper userpoints values.
 * @param $userpoints_txn
 *   The related userpoint transaction.
 * @param $order_id
 *   Order to add this userpoints value entry.
 *
 * @return
 *   Line item filled with the order_id and transaction value
 */
function _commerce_userpoints_discount_line_item_new() {
  // Create the new line item.
  $line_item = entity_create('commerce_line_item', array(
    'type' => 'userpoints',
    'quantity' => 1,
  ));

  return $line_item;
}

function commerce_userpoints_discount_line_item_populate(&$line_item, $order_id, $userpoints_txn, $currency, $label, $multiply = FALSE) {
  if (!($line_item instanceof EntityMetadataWrapper)) {
    $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);
  }
  
  $line_item_wrapper->order_id = $order_id;
  $line_item_wrapper->commerce_userpoints_discount_txn = $userpoints_txn['txn_id'];
  $line_item_wrapper->line_item_label = t($label);
  $line_item_wrapper->commerce_unit_price->currency_code = $currency;
  $line_item_wrapper->commerce_unit_price->amount =
    $multiply ? intval($userpoints_txn['points']) * 100 : intval($userpoints_txn['points']);
  $line_item_wrapper->commerce_unit_price->data = commerce_price_component_add(
      $line_item_wrapper->commerce_unit_price->value(),
    'userpoints',
    $line_item_wrapper->commerce_unit_price->value(),
    TRUE,
    FALSE
  );

  // Return the line item.
  return $line_item_wrapper->value();
}

/**
 * Saves the line item in the database and add it to the appropriate order
 * @param  $line_item
 * @return void
 */
function commerce_userpoints_discount_line_item_save($line_item) {
  commerce_line_item_save($line_item);
  $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);
  $order = commerce_order_load($line_item_wrapper->order_id->value());

  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
  $order_wrapper->commerce_line_items[] = $line_item;
  $order_wrapper->save();
}

/**
 * Copied from Commerce_shipping
 * Delete all shipping line items on an order.
 *
 * @param $order
 *  The order object to delete the shipping line items from.
 */
function commerce_userpoints_discount_clear_order($order_id) {
  $order = commerce_order_load($order_id);
  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
  // When deleting more than one line item, metadata_wrapper will give problems
  // if deleting while looping through the line items. So first remove from order
  // and then delete the line items.
  $line_items_to_delete = array();
  foreach ($order_wrapper->commerce_line_items as $delta => $line_item_wrapper) {
    if ($line_item_wrapper->type->value() == 'userpoints') {
      $line_items_to_delete[] = $line_item_wrapper->line_item_id->value();
      $order_wrapper->commerce_line_items->offsetUnset($delta);
    }
  }
  $order_wrapper->save();
  // Delete line items.
  foreach ($line_items_to_delete as $line_item_id) {
    commerce_line_item_delete($line_item_id);
  }
}

/**
 * Implements hook_entity_delete
 * When a line item of userpoints type is delete, we set the related userpoints transaction to Declined status
 * @param  $entity
 * @param  $type
 * @return void
 */
function commerce_userpoints_discount_entity_delete($entity, $type) {
  if($type == 'commerce_line_item') {
    if($entity->type == 'userpoints') {
      //Get the existing transaction
      $txn_field = field_get_items('commerce_line_item', $entity, 'commerce_userpoints_discount_txn');

      //Update the userpoints transaction
      $userpoints_params = array(
        'txn_id' => $txn_field[0]['value'],
        'status' => USERPOINTS_TXN_STATUS_DECLINED,
      );

      $result = userpoints_userpointsapi($userpoints_params);
    }
  }
}

/**
 * Implements hook_entity_create
 * When a line item of userpoints type is created, we create a userpoint transaction
 * @param  $entity
 * @param  $type
 * @return void
 */
function commerce_userpoints_discount_entity_insert($entity, $type) {
/*  if($type == 'commerce_line_item') {
    if($entity->type == 'userpoints') {

      $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $entity);
      $order = commerce_order_load($line_item_wrapper->order_id);

      //Create the userpoints transaction
      $userpoints_params = array(
        'points' => floatval($line_item_wrapper->commerce_unit_price->amount) / 100,
        'moderate' => FALSE,
        'uid' => $order->uid,
        'time_stamp' => REQUEST_TIME,
        'operation' => t('Using credit for purchase'),
        'tid' => variable_get('commerce_userpoints_discount_default_termid'),
        'expirydate' => NULL,
        'description' => t('User credit'),
        'display' => FALSE,
        'entity_id' => $order->order_id,
        'entity_type' => 'commerce_order',
      );

      $result = userpoints_userpointsapi($userpoints_params);
      $line_item_wrapper->commerce_userpoints_discount_transaction = $result['transaction']['txn_id'];
      $line_item_wrapper->save();
    }
  }*/
}

function commerce_userpoints_discount_commerce_price_component_type_info() {
  return array(
    'userpoints' => array(
      'title' => t('Royalties'),
      'display_title' => t('Royalties'),
      'weight' => 1000,
    ),
  );
}

function commerce_userpoints_discount_form_alter(&$form, &$form_values, $form_id) {
  
  if (strpos($form_id, 'commerce_checkout_form_checkout') === 0) {
    $form['cart_contents']['#prefix'] = '<div id="cup-available-credit-div">';
    $form['cart_contents']['#suffix'] = '</div>';
  };
}

function commerce_userpoints_discount_use_credit_callback_all($form, $form_state) {
  commerce_userpoints_discount_use_credit_callback($form, $form_state, TRUE);
}

function commerce_userpoints_discount_use_credit_callback_input($form, $form_state) {
  commerce_userpoints_discount_use_credit_callback($form, $form_state, FALSE);
}

function commerce_userpoints_discount_remove_credit_callback($form, $form_state) {
  $order = $form_state['order'];
  commerce_userpoints_discount_clear_order($order->order_id);
}

function commerce_userpoints_discount_use_credit_callback($form, $form_state, $use_all_credit) {
  $order = $form_state['order'];
  $cur_user_points = userpoints_get_current_points(NULL, variable_get('commerce_userpoints_discount_default_termid'));

  //If the current user is out of points, we leave directly
  if($cur_user_points == 0) return;

  //Retrieve the order total for selected components
  $order_total = 0;
  $commerce_order_total_field = field_get_items('commerce_order', $order, 'commerce_order_total');
  foreach($commerce_order_total_field[0]['data']['components'] as $price_component) {
    if(array_key_exists($price_component['name'], variable_get('commerce_userpoints_discount_total_price_components'))) {
      $order_total += floatval($price_component['price']['amount']) / 100; //TODO:make the 100 variable, based on the decimal settings
    }
   // dpm($price_component, "price component");
  }

  if($use_all_credit) {
    $points_to_use = $cur_user_points >= $order_total ? $order_total : $cur_user_points;
  }
  else {
    $points_to_use = floatval($form_state['values']['commerce_userpoints_discount']['cup_credit_amount']);

    if(intval($form_state['values']['commerce_userpoints_discount']['cup_credit_amount']) > $cur_user_points) {
      form_set_error('cup_credit_amount', t("You don't have enough credit"));
      return FALSE;
    }

    if(intval($form_state['values']['commerce_userpoints_discount']['cup_credit_amount']) < 0) {
      form_set_error('cup_credit_amount', t("The amount should be a positive value"));
      return FALSE;
    }

    if(intval($form_state['values']['commerce_userpoints_discount']['cup_credit_amount']) > $order_total) {
      form_set_error('cup_credit_amount', t("Too much !"));
      return FALSE;
    }
  }

  //If there is "no points" to use, we leave directly
  if($points_to_use == 0)
    return;
  
  $line_item_id = commerce_userpoints_discount_order_has_userpoint_line_item($order->order_id);

  //If there is no existing userpoints line item, we create a new one
  if($line_item_id == NULL) {
    //Create the line item
    $line_item = commerce_userpoints_discount_line_item_factory_new($order->order_id);

    //Create the userpoints transaction
    $userpoints_params = array(
      'points' => $points_to_use * -1,
      'uid' => $order->uid,
      'operation' => 'commerce_userpoints_discount_credit',
      'tid' => variable_get('commerce_userpoints_discount_default_termid', userpoints_get_default_tid()),
      'display' => FALSE,
      'entity_id' => $order->order_id,
      'entity_type' => 'commerce_order',
    );

    $result = userpoints_userpointsapi($userpoints_params);

    if($result['status'] == FALSE) {
      form_set_error('Sorry, you cannot use your !points right now. Please contact us for more information', userpoints_translation());
      return FALSE;
    }

    $label = "User credit";
    commerce_userpoints_discount_line_item_populate(
      $line_item, $order->order_id,
      $result['transaction'], commerce_default_currency(), $label, TRUE);

    //TODO: Should test if the line item has been correctly created
    commerce_userpoints_discount_line_item_save($line_item);
  }
  else { //If there is an existing userpoints line item for this order,
    //we load it to get its userpoints transaction id
    $line_item = commerce_line_item_load($line_item_id);

    //Get the existing transaction
    $txn_field = field_get_items('commerce_line_item', $line_item, 'commerce_userpoints_discount_transaction');

    //Clear out the old $line_item
    commerce_userpoints_discount_clear_order($order->order_id);
    unset($line_item);

    //Update the userpoints transaction
    $userpoints_params = array(
      'points' => intval($points_to_use) * -1,
      'txn_id' => $txn_field[0]['value'],
      'status' => 0,
    );
    $result = userpoints_userpointsapi($userpoints_params);

    if($result['status'] == FALSE) {
      form_set_error('Sorry, you cannot use your !points right now. Please contact us for more information');
      return FALSE;
    }

    //Create the new line item
    $line_item = commerce_userpoints_line_item_factory_new($order->order_id);

    $label = "User credit";
    commerce_userpoints_line_item_populate(
      $line_item, $order->order_id,
      $result['transaction'], commerce_default_currency(), $label, TRUE);

    //TODO: Should test if the line item has been correctly created
    commerce_userpoints_line_item_save($line_item);
  }
}